repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Use the latest stable version of Black
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile, black]
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2  # Use the latest stable version of autopep8
    hooks:
      - id: autopep8
